version: "3"

services:
  # Maven build container
  maven-builder:
    image: maven:3.8-openjdk-8
    volumes:
      - ./CRM项目/api/crm:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean package -DskipTests
    
  # Node.js build container for CRM frontend
  crm-frontend-builder:
    image: node:14
    volumes:
      - ./CRM项目/web/crm:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
    
  # Node.js build container for CP frontend
  cp-frontend-builder:
    image: node:14
    volumes:
      - ./CRM项目/web/cp-web:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
